deployment:
  replicaset: 2
  imagename: philiprime97/awsviewer
  imagetag: v1

service:
  # type: ClusterIP
  port: 80
  targetport: 5001

ingress:
  enabled: true
  ingressClassName: nginx
  host: awsviewer.com   

aws:
  accessKeyId: AWS_ACCESS_KEY_ID
  secretAccessKey: AWS_SECRET_ACCESS_KEY
  region: AWS_DEFAULT_REGION
