deployment:
  replicaset: 2
  imagename: philiprime97/awsviewer
  imagetag: v1

service:
  # type: ClusterIP
  port: 80
  targetport: 5001

ingress:
  enabled: true
  ingressClassName: nginx
  host: awsviewer.com   

aws:
  accessKeyId: ""
  secretAccessKey: ""
  region: "us-east-1"
