apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }} #from RELEASE NAME
spec:
  selector:
    {{- include "app.labels" . | nindent 4 }}
  type: {{- if .Values.ingress.enabled }} ClusterIP {{- else }} LoadBalancer {{- end }}
  ports:  #from values
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetport }}
